<?php
/**
 * VibeBuy Loader Class
 *
 * @package VibeBuy
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class VibeBuy_Loader {

	/**
	 * Main Loader Init.
	 */
	public function init() {
		// 0. Load Textdomain
		load_plugin_textdomain( 'vibebuy-order-connect-lite', false, dirname( plugin_basename( __FILE__, 2 ) ) . '/languages' );

		// 1. Load Core Components
		require_once VIBEBUY_PLUGIN_DIR . 'inc/class-vibebuy-admin.php';
		require_once VIBEBUY_PLUGIN_DIR . 'inc/class-vibebuy-api.php';
		require_once VIBEBUY_PLUGIN_DIR . 'inc/class-vibebuy-frontend.php';
		require_once VIBEBUY_PLUGIN_DIR . 'inc/class-vibebuy-shortcode.php';
		require_once VIBEBUY_PLUGIN_DIR . 'inc/class-vibebuy-notices.php';
		require_once VIBEBUY_PLUGIN_DIR . 'inc/class-vibebuy-templates.php';


		// 2. Load Integrations
		require_once VIBEBUY_PLUGIN_DIR . 'inc/integrations/class-vibebuy-woocommerce.php';
		require_once VIBEBUY_PLUGIN_DIR . 'inc/integrations/class-vibebuy-wpml.php';
		require_once VIBEBUY_PLUGIN_DIR . 'inc/integrations/class-vibebuy-cache.php';

		// 3. Initialize Components
		( new VibeBuy_Admin() )->init();
		( new VibeBuy_Frontend() )->init();
		( new VibeBuy_Shortcode() )->init();
		( new VibeBuy_Notices() )->init();
		( new VibeBuy_WooCommerce() )->init();

		( new VibeBuy_WPML() )->init();
		( new VibeBuy_Cache() )->init();
		
		// API is initialized via its own class hooks if any, or static init
		// Usually REST API routes are registered on 'rest_api_init'
		$api = new VibeBuy_API();
		add_action( 'rest_api_init', array( $api, 'register_routes' ) );

		// Filter for module scripts (required for Vite)
		add_filter( 'script_loader_tag', array( $this, 'add_module_to_script' ), 10, 3 );
	}

	/**
	 * Add type="module" to Vite scripts.
	 */
	public function add_module_to_script( $tag, $handle, $src ) {
		if ( in_array( $handle, array( 'vibebuy-admin-js', 'vibebuy-widget-js' ), true ) ) {
			return str_replace( '<script ', '<script type="module" ', $tag );
		}
		return $tag;
	}


	/**
	 * Helper function to read the manifest.json file generated by Vite.
	 * 
	 * @param string $entry_path The path to the entry file (e.g., src/App.jsx)
	 * @return array|false Returns the asset data array or false if not found.
	 */
	public static function get_vite_asset( $entry_path ) {
		$manifest_path = VIBEBUY_PLUGIN_DIR . 'assets/.vite/manifest.json';

		// Fallback for older Vite versions
		if ( ! file_exists( $manifest_path ) ) {
			$manifest_path = VIBEBUY_PLUGIN_DIR . 'assets/manifest.json';
		}

		if ( ! file_exists( $manifest_path ) ) {
			return false;
		}

		$manifest = json_decode( file_get_contents( $manifest_path ), true );

		if ( isset( $manifest[ $entry_path ] ) ) {
			$asset = $manifest[ $entry_path ];
			$css_files = isset( $asset['css'] ) ? $asset['css'] : array();

			if ( isset( $asset['imports'] ) ) {
				foreach ( $asset['imports'] as $import_key ) {
					if ( isset( $manifest[ $import_key ]['css'] ) ) {
						$css_files = array_merge( $css_files, $manifest[ $import_key ]['css'] );
					}
				}
			}

			$asset['css'] = array_unique( $css_files );
			return $asset;
		}

		return false;
	}
}

